title: Chandrani Lab - Computational Biology & Data Science
author: Pratik Chandrani
tagline: Computational Biology & Data Science
description: Chandrani Lab, Computational Biology, Bioinformatics, and Crosstalk Lab, KS-121, ACTREC - Tata Memorial Centre, Kharghar, Navi Mumbai, India.
baseurl: ""
url: "http://pratikchandrani.github.io"
type: website
image:
  path: /assets/img/pratik_chandrani.png
  height: 200
  width: 200

google_analytics: G-Z7EKMZLYJ3

include:
  - _pages

sass_dir: ./_sass

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM  # Github Flavored Markdown
  hard_wrap: false
  syntax_highlighter: rouge

twitter_username: pratikchandrani
github_username:  pratikchandrani
linkedin_username: pratik-chandrani-phd-b550b5112
youtube_username: pratikchandrani
instagram_username: pratikchandrani
scholar_id: JALyxVsAAAAJ

social:
  name: Pratik Chandrani
  links:
    - https://twitter.com/pratikchandrani
    - https://www.linkedin.com/in/pratik-chandrani-phd-b550b5112
    - https://github.com/pratikchandrani
    - https://instagram.com/pratikchandrani
    - https://youtube.com/c/pratikchandrani

# Blog settings
blog_url: /blog
permalink: /blog/:year/:month/:day/:title/
show_excerpts: true
paginate: 10
paginate_path: /blog/page/:num

# Default front matter
defaults:
  - scope:
      path: "blog/page"
    values:
      sitemap: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Comments
disqus:
  shortname: pratikchandrani

# Collections
collections:
  pages:
    output: true
    permalink: /:name

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CLAUDE.md
  - README.md
  - Makefile
  - nul
