title: Pratik Chandrani, Computational Biologist & Data Scientist
author: Pratik Chandrani
tagline: Computational Biologist & Data Scientist
description: Chandrani Lab, Computational Biology, Bioinformatics, and Crosstalk Lab, KS-121, ACTREC - Tata Memorial Centre, Kharghar, Navi Mumbai, India.
baseurl: ""
url: "http://pratikchandrani.github.io"
type: website
image:
  path: /assets/img/pratik_chandrani.png
  height: 200
  width: 200

google_analytics: G-Z7EKMZLYJ3

include:
  - _pages

sass_dir: ./_sass

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM  # Github Flavored Markdown
  hard_wrap: false
  syntax_highlighter: rouge

twitter_username: pratikchandrani
github_username:  pratikchandrani
linkedin_username: pratik-chandrani-phd-b550b5112
youtube_username: pratikchandrani
instagram_username: pratikchandrani
scholar_id: JALyxVsAAAAJ

social:
  name: Pratik Chandrani
  links:
    - https://twitter.com/pratikchandrani
    - https://www.linkedin.com/in/pratik-chandrani-phd-b550b5112
    - https://github.com/pratikchandrani
    - https://instagram.com/pratikchandrani
    - https://youtube.com/c/pratikchandrani

# blog
blog_url: /blog
permalink: /blog/:year/:month/:day/:title/
show_excerpts: True
paginate: 5
paginate_path: blog/page/:num
defaults:
  - scope:
      path: "blog/page"
    values:
      sitemap: false
disqus:
  shortname: pratikchandrani

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
